#pragma once
// globals.h

//#define OLD_DEBUG
//#define DEBUG_INDEXER
//#define DEBUG_LINK
//#define DEBUG_DATABASE
//#define DEBUG_HTTPCLIENT
//#define DEBUG_INDEXER_AND_DEBUG_HTTPCLIENT
//#define DEBUG_SPIDER
//#define DEBUG_THREAD_POOL
//#define DEBUG_HTTPS_CLIENT
//#define DEBUG_HTTP_SERVER
//#define DEBUG_WORD_SEARCH_ENGINE_DATA_BASE

//#define DEBUG_PRINT_DATA
//#define DEBUG_GET_URL

#define MAX_NUMBER_OF_LINKS_ON_ONE_PAGE 9
#define MAX_NUMBER_OF_WORDS_TO_SEARCH_IN_THE_DATABASE 3
